from crawl_vnn import get_content_post
from crawl_vnn import get_list_post
from crawl_vnn import crawl_content_of_list_post
from crawl_vnn import get_list_link
from crawl_vnn import get_file_name
from crawl_vnn import convert_json_create_file
